lib/crawler_web/router.ex
defmodule CrawlerWeb.Router do
  use CrawlerWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
  end

  scope "/", CrawlerWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index
  end

  scope "/", CrawlerWeb do
    pipe_through [:browser, :protected]

    resources "/tenders", TenderController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrawlerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CrawlerWeb.Telemetry
    end
  end
end

lib/crawler_web/views/pow/registration_view.ex
defmodule CrawlerWeb.Pow.RegistrationView do
  use CrawlerWeb, :view

  
end

lib/crawler_web/views/pow/session_view.ex
defmodule CrawlerWeb.Pow.SessionView do
  use CrawlerWeb, :view
end

lib/crawler_web/templates/pow/session/new.html.eex
<h1>Войти</h1>
<div class="col-6">
<%= form_for @changeset, @action, [as: :user], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
<div class="mb-3">
  <%= label f, Pow.Ecto.Schema.user_id_field(@changeset), class: "form-label" %>
  <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), class: "form-control" %>
  <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
</div>
<div class="mb-3">
  <%= label f, :password, class: "form-label" %>
  <%= password_input f, :password, class: "form-control" %>
  <%= error_tag f, :password %>
</div>
  <div>
    <%= submit "Войти", class: "btn btn-primary" %>
  </div>

<% end %>
 

<span><%= link "Регистрация", to: Routes.pow_registration_path(@conn, :new) %></span>
<span> | </span>
<span><%= link "Забыл пароль", to: Routes.pow_reset_password_reset_password_path(@conn, :new) %></span>
</div>


<%= form_for @changeset, Routes.tender_path(@conn, :create), fn f -> %>
  Имя: <%= text_input f, :name %>
<% end %>

<%= f = form_for @changeset, Routes.tender_path(@conn, :create) %>
  Name: <%= text_input f, :name %>

<div class="mb3">
123
</div>
<div class="mb-3">

<select id="user_roles" name="user[roles][]", class="btn btn-secondary dropdown-toggle-split">
    <option value="1">Admin</option>
    <option value="2">Power User</option>
    <option value="3">ловыарлываорывоар</option>
    <option value="4" selected="selected">крпвкпукпкуыпкупкупук</option>
    <option value="5">пукпупукпу</option>
    <option value="6">453453434</option>
    </select>
</div>


<div class="mb-3">
<select id="user_roles" name="user[roles][]">
    <option value="1" selected="selected">Admin</option>
    <option value="2">Power User</option>
    </select>
</div>
<div class="mb-3">
 <optgroup label="Europe">
      <option>UK</option>
      <option>Sweden</option>
      <option>France</option>
    </optgroup>
</div>


<div class="mb-3">
<div>
<input id="user_role_admin" name="user[role]" type="radio" value="admin">
</div>
<div>
<input type="reset" value="Reset">
</div>
<div>
<input type="reset" value="Reset" class="btn">
</div>


<div>

</div>
<div>
<select id="user_age" name="user[age]">
    <option value="0">0</option>
    ...
    <option value="120">120</option>
    </select>
</div>
<div>
<select id="user_role" name="user[role]">
    <option value="admin">Admin</option>
    <option value="user">User</option>
    </select>
</div>
<div>
<select id="user_role" name="user[role]">
    <option value="admin" disabled="disabled">Admin</option>
    <option value="user">User</option>
    </select>

</div>
<div>
<select id="user_role" name="user[role]">
    <option value="">Choose your role</option>
    <option value="admin">Admin</option>
    <option value="user">User</option>
    </select>
</div>
<div>

</div>
<div>

</div>

</div>